### ISSUE TITLE
Roadmap 0.3.0

### ISSUE THREAD

**Issue by bcessa** [mxabierto/buda#44]
#### Tareas a Realizar
- [ ] Obtener el __puerto__ utilizado para los agentes que corren __dentro de contenedores__ ( #48 )
- [ ] Agregar __documentación__ para cada componente ( #43 )
- [ ] Agregar __pruebas unitarias__ para cada componente ( #3 )
- [ ] Validar soporte para __compresión de datos__ ( #49 )
- [ ] Implementar __estrategias de actualización__ ( #47 )
- [ ] Agregar __actualizaciones automáticas__ de datos ( #45 )
- [ ] __Metadata por agente__;  cada agente deberá proveer un mecanismo para consultar metadata del dataset asociado ( #2 )
- [ ] Agregar mecanismo de __seguridad y autenticación__ a los componentes `manager` y `front` ( #46 )

**Comment by carlosmaya** [comment]
@bcessa sobre este punto
`Validar soporte para compresión de datos o eliminar temporalmente hasta tener una implementación adecuada`

¿qué es lo que se va a validar? ¿cuál es la idea?

**Comment by bcessa** [comment]
La idea es:
- Todo el procesamiento de datos se realiza mediante streams
- Cuando se utiliza compresión se pasa el stream de datos por un descompresor antes de llegar al parser del agente
https://github.com/mxabierto/buda/blob/master/agent/buda_agent.js#L117-L119

El problema es:
- Aparentemente al utilizar el compresor el flujo de eventos normal del procesamiento del stream se altera y produce inconsistencia, lo que necesito hacer es validar mucho mas detalladamente y verificar si puedo implementarlo de forma confiable o deshabilitarlo temporalmente y priorizarlo para el siguiente release.

@mxabierto/core-team

**Comment by bcessa** [comment]
Se movio a PR #50
